title: "Data & Biology Portfolio"
description: "Bioinformatics portfolio showcasing projects and technical writings"
url: "https://ataulhaleem.github.io"
baseurl: "/portfolio"
github_username: ataulhaleem
email: ataulhaleem@gmail.com

theme: minima

# Enable pages collection
collections:
  pages:
    output: true
    permalink: /:path/

# Default layout for pages
defaults:
- scope:
    path: "_pages"
  values:
    layout: page

# Build settings
plugins:
- jekyll-feed
