# _config.yml
title: "Data & Biology Portfolio"
description: "Bioinformatics portfolio showcasing projects and technical writings"
url: "https://ataulhaleem.github.io" # Your base URL
github_username: ataulhaleem

# Theme - 'minima' is standard and reliable
theme: minima

# Build settings
plugins:
  - jekyll-feed
